### ISSUE TITLE
Add Zenodo integration

### ISSUE THREAD

**Issue by Cmurilochem** [GalerkinToolkit/GalerkinToolkit.jl#104]
Example in: https://github.com/fair-workflows/nanopub

**Comment by raar1** [comment]
I've set up publishing of this repo on Zenodo (every time a release is made, Zenodo will grab it and give it a DOI automatically). We need to make a new tagged release to get the first DOI, which we can then put in CITATION.cff etc.

@fverdugo Are you in favour of us making e.g. a v0.2.1 release so that we can finish this process? As there are no code changes there would be no need to go through registering it with the Julia pkg reg.

**Comment by fverdugo** [comment]
great! NB. all releases should be done via the julia registrator to not mess things up. It also automatically generates a tag on the Github repo, which should then trigger the zenodo.

I can try tomorrow.

**Comment by raar1** [comment]
> NB. all releases should be done via the julia registrator to not mess things up.

Ah ok, got it.
